### ISSUE TITLE
前端部署问题

### ISSUE THREAD

**Issue by yunwenlong** [goufaning/permission#1]
你好，我想将vue进行打包，然后放在springboot里一起运行，请问，我需要怎么部署？目前分开部署已经得到了实现。

**Comment by yunwenlong** [comment]
sys_role_permission  这张表也没有，麻烦给补充一下吧。

**Comment by goufaning** [comment]
你可以将Vue项目下的dist文件夹中的所有文件拷贝到Spring Boot中的static文件夹中试试。
项目中并没有sys_role_permission这个表，叫做sys_role_menu，其实是同一个表。
